#!/usr/bin/env python3
"""Asset pipeline for CF Stick (StickS3, 240x135 landscape).

scene_change_gifs/{thinking,getting_lottery}.gif -> resize 240x135 ->
palette quantize -> frame cap -> C array headers in src/assets/.
Also generates a short chime WAV as a C array.

Requires Pillow: stick-dev/.venv/bin/pip install pillow
Usage: python3 tools/make_assets.py
"""
import io
import math
import struct
import wave
from pathlib import Path

from PIL import Image, ImageSequence

ROOT = Path(__file__).resolve().parents[3]          # moneyGod repo root
SRC_GIFS = {
    # name -> (source, palette colors)
    "gif_idle":  (ROOT / "scene_change_gifs/thinking.gif", 16),
    "gif_shake": (ROOT / "scene_change_gifs/getting_lottery.gif", 64),
}
OUT_DIR = Path(__file__).resolve().parents[1] / "src/assets"
W, H = 240, 135
MAX_FRAMES = 30      # frame cap to keep flash usage in check


def to_c_array(name: str, data: bytes) -> str:
    lines = [f"/* generated by make_assets.py, {len(data)} bytes */",
             "#pragma once", "#include <stdint.h>",
             f"const uint8_t {name}[] = {{"]
    for i in range(0, len(data), 16):
        lines.append("  " + ",".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",")
    lines.append("};")
    lines.append(f"const uint32_t {name}_len = {len(data)};")
    return "\n".join(lines) + "\n"


def convert_gif(name: str, src: Path, colors: int) -> None:
    im = Image.open(src)
    frames = []
    for frame in ImageSequence.Iterator(im):
        rgb = frame.convert("RGB").resize((W, H), Image.LANCZOS)
        pal = rgb.quantize(colors=colors, method=Image.MEDIANCUT, dither=Image.NONE)
        # drop inherited transparency/disposal to avoid Pillow save errors
        pal.info.pop("transparency", None)
        pal.info.pop("disposal", None)
        frames.append(pal)
    step = max(1, math.ceil(len(frames) / MAX_FRAMES))
    frames = frames[::step]
    dur = im.info.get("duration", 100) * step
    buf = io.BytesIO()
    frames[0].save(buf, format="GIF", save_all=True, append_images=frames[1:],
                   duration=dur, loop=0, optimize=True, disposal=1)
    data = buf.getvalue()
    (OUT_DIR / f"{name}.h").write_text(to_c_array(name, data))
    print(f"{name}: {len(frames)} frames, {len(data) / 1024:.0f} KB")


def make_chime() -> None:
    """0.6s two-tone rising chime, 16bit 22050Hz mono WAV."""
    sr, dur = 22050, 0.6
    samples = []
    for i in range(int(sr * dur)):
        t = i / sr
        f = 880 if t < 0.25 else 1320
        env = math.exp(-4 * t)
        samples.append(int(28000 * env * math.sin(2 * math.pi * f * t)))
    buf = io.BytesIO()
    with wave.open(buf, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(sr)
        w.writeframes(b"".join(struct.pack("<h", s) for s in samples))
    data = buf.getvalue()
    (OUT_DIR / "wav_shake.h").write_text(to_c_array("wav_shake", data))
    print(f"wav_shake: {len(data) / 1024:.0f} KB")


if __name__ == "__main__":
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, (src, colors) in SRC_GIFS.items():
        convert_gif(name, src, colors)
    make_chime()
