[env:m5stack-sticks3]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.partitions = default_8MB.csv
board_build.arduino.memory_type = qio_opi
build_flags =
    -DESP32S3
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps =
    m5stack/M5Unified@^0.2.7
    bitbank2/AnimatedGIF@^2.1.1
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
test_ignore = test_native

[env:native]
platform = native
build_flags = -std=c++14
test_filter = test_native
