#!/usr/bin/env python3
"""Generate a compact Unicode->GBK mapping table covering the full GB2312 set.

v2: no longer scans qianpu_data.c — the fortune text now comes from the LLM at
runtime, so the printer must be able to encode any GB2312 character
(symbols area 0xA1-0xA9 + hanzi area 0xB0-0xF7).
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "../TuyaOpen/apps/cyber_fortune/src/assets/fortune_gbk_map.c")

rows = []
for hi in range(0xA1, 0xF8):
    for lo in range(0xA1, 0xFF):
        raw = bytes([hi, lo])
        try:
            ch = raw.decode("gb2312")
        except UnicodeDecodeError:
            continue
        rows.append((ord(ch), hi, lo, ch))

# Sorted by unicode codepoint for binary search on the firmware side
rows.sort(key=lambda r: r[0])

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    f.write("/* Auto-generated by tools/gen_gbk_map.py - Unicode->GBK table, full GB2312.\n"
            " * Sorted by unicode codepoint for binary search. DO NOT EDIT BY HAND. */\n")
    f.write("#include <stdint.h>\n\n")
    f.write("typedef struct {\n    uint16_t unicode;\n    uint8_t  gbk_hi;\n    uint8_t  gbk_lo;\n} gbk_map_entry_t;\n\n")
    f.write("const gbk_map_entry_t g_gbk_map[] = {\n")
    for cp, hi, lo, ch in rows:
        f.write("    {0x%04X, 0x%02X, 0x%02X}, /* %s */\n" % (cp, hi, lo, ch))
    f.write("};\n\n")
    f.write("const int g_gbk_map_count = %d;\n" % len(rows))

print("entries: %d -> %s" % (len(rows), os.path.normpath(OUT)))
