#!/usr/bin/env python3
"""Embed web/ assets and generate portal_web_attach() implementation."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

PAYLOAD_FILES = frozenset({"provision_ok.html"})
CONTENT_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".js": "application/javascript; charset=utf-8",
}


def symbol_from_relpath(relpath: str) -> str:
    stem = re.sub(r"[^0-9a-zA-Z_]", "_", relpath.replace("/", "_").replace(".", "_"))
    if stem and stem[0].isdigit():
        stem = f"_{stem}"
    return f"__portal_{stem}"


def escape_c_string_piece(piece: str) -> str:
    return (
        piece.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def c_string_literal(text: str) -> str:
    chunks: list[str] = []
    parts = text.split("\n")

    for index, part in enumerate(parts):
        if index == len(parts) - 1:
            if part:
                chunks.append(f'    "{escape_c_string_piece(part)}"')
            break

        chunks.append(f'    "{escape_c_string_piece(part)}\\n"')

    return "\n".join(chunks)


def route_path_for(relpath: str) -> str | None:
    if relpath in PAYLOAD_FILES:
        return None

    suffix = Path(relpath).suffix.lower()
    if suffix not in CONTENT_TYPES:
        return None

    if relpath == "index.html":
        return "/"

    if relpath.startswith("assets/"):
        return f"/{relpath}"

    if suffix == ".html":
        return f"/{Path(relpath).name}"

    return None


def content_type_for(relpath: str) -> str:
    suffix = Path(relpath).suffix.lower()
    if suffix not in CONTENT_TYPES:
        raise ValueError(f"unsupported web asset type: {relpath}")
    return CONTENT_TYPES[suffix]


def discover_assets(web_root: Path) -> tuple[list[dict], list[dict]]:
    static_entries: list[dict] = []
    payload_entries: list[dict] = []

    for path in sorted(web_root.rglob("*")):
        if not path.is_file():
            continue

        relpath = path.relative_to(web_root).as_posix()
        if relpath in PAYLOAD_FILES:
            payload_entries.append(
                {
                    "relpath": relpath,
                    "symbol": symbol_from_relpath(relpath),
                }
            )
            continue

        route_path = route_path_for(relpath)
        if route_path is None:
            continue

        static_entries.append(
            {
                "relpath": relpath,
                "path": route_path,
                "content_type": content_type_for(relpath),
                "symbol": symbol_from_relpath(relpath),
            }
        )

    if not static_entries:
        raise ValueError(f"no static web assets found under {web_root}")

    return static_entries, payload_entries


def read_asset_text(web_root: Path, relpath: str) -> str:
    text = (web_root / relpath).read_text(encoding="utf-8")
    if not text.endswith("\n"):
        text += "\n"
    return text


def render_header() -> str:
    return """/**
 * @file portal_web_assets.h
 * @brief Embedded HTTP portal web assets API.
 * @note Generated by tools/embed_web_assets.py. Do not edit manually.
 * @copyright Copyright (c) 2021-2026 Tuya Inc.
 */
#ifndef __PORTAL_WEB_ASSETS_H__
#define __PORTAL_WEB_ASSETS_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "http_site.h"

/**
 * @brief Register embedded portal static routes on an HTTP site.
 * @param[in] site HTTP site handle.
 * @return OPRT_OK on success.
 */
OPERATE_RET portal_web_attach(HTTP_SITE_HANDLE_T site);

/**
 * @brief Get provision success page HTML.
 * @return provision success page body.
 */
const char *portal_web_provision_ok_html(void);

#ifdef __cplusplus
}
#endif

#endif /* __PORTAL_WEB_ASSETS_H__ */
"""


def render_source(static_entries: list[dict], payload_entries: list[dict], web_root: Path) -> str:
    lines = [
        "/**",
        " * @file portal_web_assets.c",
        " * @brief Embedded HTTP portal web assets.",
        " * @note Generated by tools/embed_web_assets.py. Do not edit manually.",
        " * @copyright Copyright (c) 2021-2026 Tuya Inc.",
        " */",
        '#include "portal_web_assets.h"',
        "",
    ]

    for entry in static_entries + payload_entries:
        text = read_asset_text(web_root, entry["relpath"])
        lines.append(f"/* Source: web/{entry['relpath']} */")
        lines.append(f"static const char {entry['symbol']}[] =")
        lines.append(c_string_literal(text) + ";")
        lines.append("")

    lines.extend(
        [
            "static const HTTP_SITE_STATIC_ROUTE_T s_portal_static_routes[] = {",
        ]
    )

    for entry in static_entries:
        lines.append(
            '    {"GET", "'
            + entry["path"]
            + '", "200 OK", "'
            + entry["content_type"]
            + '", '
            + entry["symbol"]
            + "},"
        )

    lines.extend(
        [
            "};",
            "",
            "/**",
            " * @brief Register embedded portal static routes on an HTTP site.",
            " * @param[in] site HTTP site handle.",
            " * @return OPRT_OK on success.",
            " */",
            "OPERATE_RET portal_web_attach(HTTP_SITE_HANDLE_T site)",
            "{",
            "    return http_site_add_static_routes(site, s_portal_static_routes,",
            "                                       (uint16_t)(sizeof(s_portal_static_routes) / sizeof(s_portal_static_routes[0])));",
            "}",
            "",
        ]
    )

    provision_symbol = None
    for entry in payload_entries:
        if entry["relpath"] == "provision_ok.html":
            provision_symbol = entry["symbol"]
            break

    if provision_symbol is None:
        raise ValueError("missing payload web asset: provision_ok.html")

    lines.extend(
        [
            "/**",
            " * @brief Get provision success page HTML.",
            " * @return provision success page body.",
            " */",
            "const char *portal_web_provision_ok_html(void)",
            "{",
            f"    return {provision_symbol};",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--web-root",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "web",
        help="Directory containing portal web assets",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "src",
        help="Directory for generated C/H files",
    )
    args = parser.parse_args()

    web_root = args.web_root.resolve()
    out_dir = args.out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    static_entries, payload_entries = discover_assets(web_root)

    for entry in static_entries + payload_entries:
        asset_path = web_root / entry["relpath"]
        if not asset_path.is_file():
            raise FileNotFoundError(f"missing web asset: {asset_path}")

    (out_dir / "portal_web_assets.h").write_text(render_header(), encoding="utf-8")
    (out_dir / "portal_web_assets.c").write_text(
        render_source(static_entries, payload_entries, web_root), encoding="utf-8"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
