/**
 * @file portal_web_assets.c
 * @brief Embedded HTTP portal web assets.
 * @note Generated by tools/embed_web_assets.py. Do not edit manually.
 * @copyright Copyright (c) 2021-2026 Tuya Inc.
 */
#include "portal_web_assets.h"

/* Source: web/assets/app.js */
static const char __portal_assets_app_js[] =
    "(function () {\n"
    "  async function loadStatus() {\n"
    "    const p = document.getElementById('status');\n"
    "    if (!p) {\n"
    "      return;\n"
    "    }\n"
    "    try {\n"
    "      const r = await fetch('/api/status');\n"
    "      p.textContent = await r.text();\n"
    "    } catch (e) {\n"
    "      p.textContent = 'status request failed';\n"
    "    }\n"
    "  }\n"
    "\n"
    "  /* Setup form uses native POST; full HTML response from /api/provision replaces the page. */\n"
    "  loadStatus();\n"
    "})();\n";

/* Source: web/assets/style.css */
static const char __portal_assets_style_css[] =
    "body {\n"
    "  font-family: Arial, sans-serif;\n"
    "  background: #f2f5f7;\n"
    "  margin: 0;\n"
    "  padding: 20px;\n"
    "}\n"
    "\n"
    ".card {\n"
    "  max-width: 520px;\n"
    "  margin: auto;\n"
    "  background: #fff;\n"
    "  padding: 16px;\n"
    "  border-radius: 8px;\n"
    "  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);\n"
    "}\n"
    "\n"
    "h1 {\n"
    "  margin-top: 0;\n"
    "  font-size: 22px;\n"
    "}\n"
    "\n"
    "label {\n"
    "  display: block;\n"
    "  margin: 10px 0;\n"
    "}\n"
    "\n"
    "input {\n"
    "  width: 100%;\n"
    "  padding: 10px;\n"
    "  box-sizing: border-box;\n"
    "}\n"
    "\n"
    "button {\n"
    "  padding: 10px 16px;\n"
    "  cursor: pointer;\n"
    "  background: #2a64f6;\n"
    "  color: #fff;\n"
    "  border: none;\n"
    "  border-radius: 4px;\n"
    "}\n"
    "\n"
    "pre {\n"
    "  background: #111;\n"
    "  color: #8ef;\n"
    "  padding: 10px;\n"
    "  border-radius: 4px;\n"
    "  overflow: auto;\n"
    "}\n";

/* Source: web/index.html */
static const char __portal_index_html[] =
    "<!doctype html>\n"
    "<html>\n"
    "<head>\n"
    "  <meta charset=\"utf-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
    "  <title>TuyaOpen Setup</title>\n"
    "  <link rel=\"stylesheet\" href=\"/assets/style.css\">\n"
    "</head>\n"
    "<body>\n"
    "  <main class=\"card\">\n"
    "    <h1>TuyaOpen SoftAP Portal</h1>\n"
    "    <p>Connect your device to router Wi-Fi.</p>\n"
    "    <form id=\"wifi-form\" method=\"post\" action=\"/api/provision\">\n"
    "      <label>SSID<input id=\"ssid\" name=\"ssid\" maxlength=\"32\" required></label>\n"
    "      <label>Password<input id=\"password\" name=\"password\" maxlength=\"64\" type=\"password\"></label>\n"
    "      <button type=\"submit\">Connect</button>\n"
    "    </form>\n"
    "    <p><a href=\"/status.html\">Go to status page</a></p>\n"
    "  </main>\n"
    "  <script src=\"/assets/app.js\"></script>\n"
    "</body>\n"
    "</html>\n";

/* Source: web/status.html */
static const char __portal_status_html[] =
    "<!doctype html>\n"
    "<html>\n"
    "<head>\n"
    "  <meta charset=\"utf-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
    "  <title>Device Status</title>\n"
    "  <link rel=\"stylesheet\" href=\"/assets/style.css\">\n"
    "</head>\n"
    "<body>\n"
    "  <main class=\"card\">\n"
    "    <h1>Device Status</h1>\n"
    "    <pre id=\"status\">loading...</pre>\n"
    "    <p><a href=\"/\">Back to setup</a></p>\n"
    "  </main>\n"
    "  <script src=\"/assets/app.js\"></script>\n"
    "</body>\n"
    "</html>\n";

/* Source: web/provision_ok.html */
static const char __portal_provision_ok_html[] =
    "<!doctype html>\n"
    "<html>\n"
    "<head>\n"
    "  <meta charset=\"utf-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
    "  <title>Provision Submitted</title>\n"
    "  <link rel=\"stylesheet\" href=\"/assets/style.css\">\n"
    "</head>\n"
    "<body>\n"
    "  <main class=\"card\">\n"
    "    <h1>Saved Successfully</h1>\n"
    "    <p>Device will switch from SoftAP to router Wi-Fi shortly.</p>\n"
    "    <p>Please reconnect your phone/computer to your router.</p>\n"
    "    <p id=\"count\">Switching in 3s...</p>\n"
    "    <p><a href=\"/status.html\">View status page</a></p>\n"
    "  </main>\n"
    "  <script>\n"
    "    (function () {\n"
    "      var n = 3;\n"
    "      var el = document.getElementById('count');\n"
    "      var t = setInterval(function () {\n"
    "        n--;\n"
    "        if (n <= 0) {\n"
    "          clearInterval(t);\n"
    "          el.textContent = 'Switching now...';\n"
    "        } else {\n"
    "          el.textContent = 'Switching in ' + n + 's...';\n"
    "        }\n"
    "      }, 1000);\n"
    "    })();\n"
    "  </script>\n"
    "</body>\n"
    "</html>\n";

static const HTTP_SITE_STATIC_ROUTE_T s_portal_static_routes[] = {
    {"GET", "/assets/app.js", "200 OK", "application/javascript; charset=utf-8", __portal_assets_app_js},
    {"GET", "/assets/style.css", "200 OK", "text/css; charset=utf-8", __portal_assets_style_css},
    {"GET", "/", "200 OK", "text/html; charset=utf-8", __portal_index_html},
    {"GET", "/status.html", "200 OK", "text/html; charset=utf-8", __portal_status_html},
};

/**
 * @brief Register embedded portal static routes on an HTTP site.
 * @param[in] site HTTP site handle.
 * @return OPRT_OK on success.
 */
OPERATE_RET portal_web_attach(HTTP_SITE_HANDLE_T site)
{
    return http_site_add_static_routes(site, s_portal_static_routes,
                                       (uint16_t)(sizeof(s_portal_static_routes) / sizeof(s_portal_static_routes[0])));
}

/**
 * @brief Get provision success page HTML.
 * @return provision success page body.
 */
const char *portal_web_provision_ok_html(void)
{
    return __portal_provision_ok_html;
}
