/**
 * @file portal_web_assets.h
 * @brief Embedded HTTP portal web assets API.
 * @note Generated by tools/embed_web_assets.py. Do not edit manually.
 * @copyright Copyright (c) 2021-2026 Tuya Inc.
 */
#ifndef __PORTAL_WEB_ASSETS_H__
#define __PORTAL_WEB_ASSETS_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "http_site.h"

/**
 * @brief Register embedded portal static routes on an HTTP site.
 * @param[in] site HTTP site handle.
 * @return OPRT_OK on success.
 */
OPERATE_RET portal_web_attach(HTTP_SITE_HANDLE_T site);

/**
 * @brief Get provision success page HTML.
 * @return provision success page body.
 */
const char *portal_web_provision_ok_html(void);

#ifdef __cplusplus
}
#endif

#endif /* __PORTAL_WEB_ASSETS_H__ */
